// packages/react/src/useGet.ts
import { useCallback, useSyncExternalStore } from 'react';
import { useStore } from './provider';

import type { Computed, State } from 'ccstate';

export function useGet<T>(atom: State<T> | Computed<T>) {
  const store = useStore();
  const subscribe = useCallback(
    (fn: () => void) => {
      const controller = new AbortController();
      store.watch(
        (get) => {
          get(atom);
          fn();
        },
        {
          signal: controller.signal,
        },
      );
      return () => {
        controller.abort();
      };
    },
    [store, atom],
  );

  return useSyncExternalStore(subscribe, () => store.get(atom));
}

// packages/solid/src/useGet.ts
import { useStore } from './provider';
import { type Computed, type State } from 'ccstate';
import { createSignal, onCleanup } from 'solid-js';

export function useGet<T>(signal$: State<T> | Computed<T>) {
  const store = useStore();
  const [value, setValue] = createSignal<T>(store.get(signal$));

  const refresh = () => {
    setValue(() => store.get(signal$));
  };
  const unsubscribe = store.watch(signal$, refresh);
  onCleanup(unsubscribe);
  refresh();

  return value;
}
